---
abstract: 'make sure only one invocation of a script is active at a time'
author:
  - 'Ben Tilly (btilly@gmail.com)'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.143240'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Sys-RunAlone
no_index:
  directory:
    - t
    - inc
requires:
  Fcntl: '0'
version: '0.13'
